### ISSUE TITLE
Links are removed from buffer when transclusions are activated?

### ISSUE THREAD

**Issue by alphapapa** [nobiot/org-transclusion#13]
I was browsing through the code and noticed that, when a transclusion link is activated, the link is removed from the buffer before the transclusion overlay is added.

Is that necessary?  Could the overlay be simply overlaid on top of the link instead?  If that worked, it would be simpler and safer.

**Comment by nobiot** [comment]
@alphapapa this is a difficult one. I agree that it is not ideal.
I would love to have a better way.

The link is deleted from the buffer, and then put into a property of the overlay (so that it can be put back).

The main reason for the design choice of removing is mainly for exporting the buffer. I would like to export the text content, and avoid exporting the link. Being able to compose long-form material from links, and then to export to PDF, Word, etc. is the goal of my implementation. 

I don't seem to be able to make an overlay on top of a link. 

John Kitchin's original sample code uses the display property of the overlay to show the text content. It is great for display, and keeps the buffer with links only.  However, it does not fulfill the requirement of export. Org export and Pandoc seem to look at the buffer, and the content of the display property is not included in the export (I think it is not part of the buffer).

Making the link invisible via a text property does not seem to work either. It will remain part of the buffer (as far as I can test in .txt file; I could not make invisible text property work with org or markdown files), so it will be exported together with the rest of the text content. 

I also tried an idea of making the link read-only. It still has the problem of being exported.

I haven't look into a way to "hide links" only when the buffer is being exported -- not sure if there is a good way for it.

It seems to me that, for this requirement, the easiest choice seems to be to insert the text content as a real buffer content, put an overlay on top of it to store various properties and visual indication of the transclusion -- and remove the link.

I need to put the link somewhere, so that I can put it back when saving the buffer, etc.  An overlay property was the natural choice. For now. 

Open for a better idea, of course. 👍

**Comment by alphapapa** [comment]
Being able to export with transcluded content is a great feature, so I understand why you're removing the link.

My concern is that, if the link is actually removed from the buffer, then when the buffer is auto-saved, it wouldn't be present in the file.  However, I'm not an expert on auto-saving. 
 Is `before-save-hook` run before auto-saving?  If so, I guess that shouldn't be a problem, because that should replace the transcluded content with the link.  I guess the issue then would be to reactivate transclusion after the auto-save.

**Comment by nobiot** [comment]
From what I have been testing, yes, auto-saving seems to also use save-buffer, which is surrounded by before- and after-save-hooks. At the moment, my version of "remove-save-add-back" seems to be working... 
I will be more careful in testing next time. I would not say I was paying enough attention to the auto-saving, even if it is turned on in my Emacs. Thank you, @alphapapa !

**Comment by flurie** [comment]
I'd like to see an option to retain links for specific purposes. A use case I'd like to try out is to have contact info on my contacts from individual files in org-roam transcluded in a single contacts.org file, but I'd like to be able to retain links to the contact's individual note. I can always include a sibling link, but it seems like overkill, and it makes some things I'd like to do in the future harder.

**Comment by nobiot** [comment]
Tricky, this one. The original link is stored as an overlay property. What is your "specific purposes"?

**Comment by nobiot** [comment]
Implemented a new approach, not relying on a link. Streamlined the syntax to use only the `#+transclude:` keyword, which you can make out of a link. I have also rearranged the program flow so that the keyword gets removed at the very end of the transclusion process -- if transclusion does not, no removal should occur.

I have also added a live-sync edit feature back as an experiment. 

I will do a video update soon. Thank you.
