### ISSUE TITLE
`package-vc-install` fails to install manual

### ISSUE THREAD

**Issue by josephmturner** [nobiot/org-transclusion#182]
To reproduce:
On Emacs 29+, run
```
(package-vc-install "https://github.com/nobiot/org-transclusion")
```
This successfully installs `org-transclusion`, but it does not install the manual.

I think that `package-vc--build-documentation` expects the docs to be at `docs/org-transclusion.org` but instead they are located at `docs/org-transclusion-manual.org`.

Perhaps there is a way to tell `package-vc` where the docs are actually located?

**Comment by josephmturner** [comment]
I attempted to solve this issue by renaming `org-transclusion-manual.org` to `org-transclusion.org`, but it didn't work. More details in [this commit message](https://github.com/josephmturner/org-transclusion/commit/cad809ed9a7e4e9976963eefcc9c0e33afb027d0).

**Comment by nobiot** [comment]
Thanks. I'd like to take a deeper look, but:

1. Emacs 29 has not been officially released. 
2. This package is shared via ELPA, thus it is considered part of Emacs -- and it can build the manual via `make`

For these two reasons, I am wondering if this issue should not be addressed via `package-vc` rather than via individual packages.

In general, I have no problem adapting a way that would work for both `package-vc` and ELPA. At this stage, I would like to wait for Emacs 29 to be officially released.

In addition... I have no idea what change is required to support the current state of `package-vc`. Do you have suggestions? I don't understand why the build process cannot find `fdl.texi`. It's in the same directory as `org-transclusion-manual.org` and `#+texinfo: @include fdl.texi` should be syntactically correct...

**Comment by josephmturner** [comment]
With `emacs -Q`, `(package-vc-install "https://github.com/nobiot/org-transclusion")` does not fail. However, the manual does not build. I have sent an email to the help-gnu-emacs mailing list, and I'll report back here with what I learn!

**Comment by nobiot** [comment]
Thank you for asking in he mailing list. Quite excited about what we might discover.

**Comment by nobiot** [comment]
Just as additional information...
This is something I set it once and have forgotten since. But ELPA is configured this way as below. This means:

1. `make org-transclusion.org` is used, [which should generate ](https://github.com/nobiot/org-transclusion/blob/main/Makefile#L1)`org-transclusion.org` from `docs/org-transclusion-manual.org`
2. ELPA then takes `docs/org-transclusion.org` as the source to generate the Info doc

https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/elpa-packages#n491
```
 (org-transclusion	:url "https://github.com/nobiot/org-transclusion"
  :make "org-transclusion.org"
  :doc "docs/org-transclusion.org"
  :readme "README.org")
```

**Comment by josephmturner** [comment]
Thank you, @nobiot! The issue is that `package-vc` doesn't currently support the `:make` package specification key.

**Comment by josephmturner** [comment]
I have submitted a [patch](https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-05/msg00368.html) to add support for `:make` and `:shell-command` spec args in `package-vc`.

And also a [separate patch](https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-05/msg00371.html) for the issue where the build process could not find `fdl.texi`.

**Comment by nobiot** [comment]
Great. Anything I should do on my end?

**Comment by nobiot** [comment]
Okay, thank you!
