### ISSUE TITLE
Would you consider modularising the extensions?

### ISSUE THREAD

**Issue by akashpal-21** [nobiot/org-transclusion#238]
Currently org-transclusion.el cannot be simply evaluated and tested -- 

org-transclusion/org-transclusion-font-lock.el
org-transclusion/org-transclusion-src-lines.el
org-transclusion/text-clone.el

The above must be evaluated before org-transclusion can finally be evaluated. Ripping apart the requirements is more cumbersome than just evaluating all the extensions together. Are all of them necessary for the core?

org-transclusion/org-transclusion.el

Great package though, do you have some optimisations in the back of your mind I can try, or you can hint for me to explore --

**Comment by nobiot** [comment]
Hi @akashpal-21 Thank you for your note.

I will come back to this thread. I want to mention two big issues: performance and infinite loop. If you could help us resolve either/both, it would be fantastic. (Can't remember the issue numbers, let me look later).

Re your point: 
> Currently org-transclusion.el cannot be simply evaluated and tested 

How about something like this below?

```
(use-package org-transclusion
  :load-path ("~/src/org-transclusion")
  :custom
  (org-transclusion-extensions nil))
```

Refer to `org-transclusion-set-extensions` and `org-transclusion-load-extensions-maybe`...

**Comment by nobiot** [comment]
@akashpal-21 

Here are the relevant issues.

- Performance issue: https://github.com/nobiot/org-transclusion/issues/106
- Infinite loop issue (reproducible): https://github.com/nobiot/org-transclusion/issues/177#issuecomment-1880265546

For the performance issue, I was playing with a caching mechanism with a hash table. I didn't make to work to improve the performance, so I put it on hold. 

For the infinite loop, I  was able to reliably reproduce the issue back then. When I went back to it now, I can only do so more intermittently. I may think of a band-aid patch for it. In any case, I need to spend more time on it.

---

With regard to your original suggestion about "modularizing", in my view, the features in this package (`.el` files) are already modular. I tried emulating what Daniel Medler has done with [`vertico`](https://github.com/minad/vertico). In it, the main feature is provided by `vertico.el` and the extensions, by each `.el` under `extensions` folder. 

As a user, you are instructed to enable (`require`) extension features as you like. In the [Extensions section of README](https://github.com/minad/vertico?tab=readme-ov-file#extensions), he provides an example of configuration with using `use-package` like this:

```emacs-lisp
(use-package vertico-directory
  :after vertico
  :ensure nil
[my omission for the rest of configuration]
)
```

I find it clean and easy enough. What I've added to `org-transclusion` is a way for the user to add extension features via `customize` with some features active by default:

![image](https://github.com/nobiot/org-transclusion/assets/12507865/26ca40d3-93dc-4760-8bd7-ee2240bd1ee7)

I think that it is a side-effect of this user convenience that a developer (like yourself) is required to do something a little more. This little more should be simply adding a source files' directory to `load-path`. Or this:

```emacs-lisp
(use-package org-transclusion
  :load-path ("~/src/org-transclusion"))
```

Perhaps I should consider a "CONTRIBUTE" notice as a guide for contribution to this package (this can be a PR, too :)). 

`text-clone` is a different to the extensions. It is separate because I have been intending to adjust it and send to Emacs upstream as a patch (I have also been asked to do so); I haven't done this yet. The feature is meant to be an extension to the built-in `text-clone-create` function in `subr.el`. This is also something I would like some help with.

I think I am still learning how to make it clear on a public repo like this where the author (me) needs help.

**Comment by nobiot** [comment]
> also regarding the infinite loop - I only triggered it once, I dont know myself how to retrigger it,

The linked issue has a detailed step-by-step repro. It would be good if you can also see if it is reproducible :)
