### ISSUE TITLE
Question about org-transclusion-indent-mode

### ISSUE THREAD

**Issue by akashpal-21** [nobiot/org-transclusion#240]
In the Manual it says that `org-transclusion-indent-mode` "supports" org-indent-mode. 
But when I add a transclusion - the indent is maintained properly in org-indent-mode : the only problem is that the fringe overlay is missing - org-transclusion-indent-mode adds support for the fringe overlay not indentation itself -- I think it is confusing in that respect.

Adding a screenrecord to show the difference

https://github.com/nobiot/org-transclusion/assets/46517170/768f67dc-5422-4f55-82bf-073fbe1e9e0b

**Comment by nobiot** [comment]
I don't seem to be able to reproduce the problem.

In this video, both buffers have `org-indent-mode` enabled (I don't normally use it). The extension to support it is turned on; that's why you see the vertical bar on the left buffer appear. 

https://github.com/nobiot/org-transclusion/assets/12507865/166f1876-3f1f-4b76-9ffc-f4e0e7d2ae31

![image](https://github.com/nobiot/org-transclusion/assets/12507865/f1a670c6-569a-4c8f-abab-fc91e16bea71)
Indent-mode support enabled.

![image](https://github.com/nobiot/org-transclusion/assets/12507865/6319f2f6-be76-4378-b11c-3b68341daa2a)
Indent-mode support disabled.

Note the vertical bar on the left side of the left buffer.
