### ISSUE TITLE
org-transclusion-before-kill is unable to clean transclusion content from copy on disk.

### ISSUE THREAD

**Issue by akashpal-21** [nobiot/org-transclusion#244]
If user saves buffer while live-sync is in progress - the actual content saved to disk will not be cleaned of transclusion content.
Combination of buffer-modified states prevent user from seeing what content is actually on disk and what is being presented in buffer.

One solution that I have implemented -- a slight modification to the org-transclusion-kill-buffer-hook

```
(defun org-transclusion-before-kill ()
  (when (and (org-transclusion-remove-all)
             (buffer-file-name))
    (set-buffer-modified-p t)
    (org-transclusion-remove-all)
    (save-buffer)
    ))
 ```
 
 original implementation
 ```
 (defun org-transclusion-before-kill ()
  (when (and (org-transclusion-remove-all)
             (buffer-file-name))
    (org-transclusion-remove-all)))
 ```
 
 Documentation removed for brevity.
 
 Thanks,
 Akash.

**Comment by nobiot** [comment]
> If user saves buffer while live-sync is in progress - the actual content saved to disk will not be cleaned of transclusion content

The manual has this note:

> Note: During live-sync edit, file’s content gets saved to the file system as is – i.e. the transcluded text will be saved instead of the ‘#+transclude:’ keyword. If you kill buffer or quit Emacs, other hooks will still remove the transclusion to keep the file clear of the transcluded copy, leaving only the keyword in the file system.

Is this issue saying that the hooks do not remove the transclusion as described in the manual?

I am a little confused because the title of this issue is about save during live-sync and yet your suggested solution is about kill-buffer. Could you please elaborate a little more?

**Comment by nobiot** [comment]
> I have also found that the kill-emacs-hooks dont function in my client- daemon setup -- in fact no buffer local kill-emacs hook function in the client-daemon setup

server-done-hook might work: https://stackoverflow.com/questions/3737207/emacsclient-hook-on-kill/3738178#3738178

**Comment by nobiot** [comment]
Instead of pressing the "X" button on your window manager, if I use `server-edit` (`C-x #`) or `save-buffers-kill-terminal` (`C-x C-c`) on emacsclient, transclusions correctly seem to get removed correctly. Is this not the case on your end?

**Comment by nobiot** [comment]
In addition... Is this issue only about Emacs running as a server and daemon? The title seems to suggest it is a generic issue and is a problem outside server and daemon. Are we talking about two different issues (one is about live-sync and the other, about server and daemon)? If so, let's have a separate issues...

**Comment by nobiot** [comment]
I am still trying to understand the issue you report here.

Let us take a step back.

The title of this issue is this:

> Saving in between live-sync prevents transclusion cleanup on kill-buffer and friends

The documentation says this:

> Note: During live-sync edit, file’s content gets saved to the file system as is

So... the behavior you are reporting as an issue seems to be the way live-sync currently works. 

And then... I am sorry that I am lost here. I cannot tell if 

1. You observe this same behavior on your end. You do not like it so are suggesting a fix

2. This documented behavior does not occur on your end.

Which case is it? Or either?

Sorry my lack of understanding of this issue is as basic as this.

**Comment by nobiot** [comment]
Please give me a basic step-by-step instruction how to reproduce the problem.
