### ISSUE TITLE
include-first-section and :hlevel n don't compose

### ISSUE THREAD

**Issue by shlevy** [nobiot/org-transclusion#47]
I have a transclusion with `:hlevel 3`, but when `org-transclusion-include-first-section` is set to `t` everything shows up at the level in the original file.

**Comment by nobiot** [comment]
Hi @shlevy, thank you for all the reports you have done. My life commitment does not really let me focus on Org-transclusion for a while (except a little procrastination here and there). 

Thank you for finding this little quirk; I will need to dig deep a little, but this does seem to be something I need to fix. It will have to wait until April or so in 2021... (I may be able to find the cause and fix more quickly, but this issue seems to require a bit more focused attention than my procrastination).

**Comment by shlevy** [comment]
Thank you, no rush for sure!
