### ISSUE TITLE
Heading collapse doesn't work with include-first-section

### ISSUE THREAD

**Issue by shlevy** [nobiot/org-transclusion#48]
If I transclude a file with `include-first-section` underneath some header and then try to collapse the header, the transcluded contents are still visible

**Comment by nobiot** [comment]
This is an expected behaviour, I think.
See the image below. I transcluded the first section including the title from another file.
The first section belongs to "H2 outside the trancluded area" headline.

I am not saying it is the most intuitive behaviour (the first section is a little tricky to treat because it does not belong to a headline). I might do something later, but at the moment, if this is what you have reported, it is expected.

![image](https://user-images.githubusercontent.com/12507865/103348969-d9d60400-4a9b-11eb-9b88-b9fe248e9c9b.png)

**Comment by shlevy** [comment]
If you collapse the `H2 outside the transcluded area`, you can still see the `Org note without headlines` content. Is that expected?

**Comment by nobiot** [comment]
Can you show me a screen capture? In this example above, I could collapse H2 as normal Org does.

**Comment by nobiot** [comment]
![image](https://user-images.githubusercontent.com/12507865/103355749-5b835d00-4aaf-11eb-8d6d-e95ba47403d6.png)

**Comment by shlevy** [comment]
Hmm interesting. I'll have to see if I hit this again and reopen if so. Though I guess it's odd in your screenshot that you can still see "headline"
