### ISSUE TITLE
[Feature Request] Is it possible display source code file link with syntax highlight?

### ISSUE THREAD

**Issue by stardiviner** [nobiot/org-transclusion#57]
I hope org-transclusion can support source code file syntax highlight,
And support file lines range like GitHub, `[[file:code.py::123-130]]` to only display 123 - 130 lines. or limit lines after `#+transclude: t :line-range 123-130` ?

**Comment by nobiot** [comment]
There are a couple of foundational changes I would need to implement first to achieve this, but it is an interesting one.
Just as a quick "mock up", I am thinking in the direction illustrated in this screen grab. Not saying this will be the implementation, but this way, the standard link syntax will not need to be changed (so that the normal Org Mode would still work.
![image](https://user-images.githubusercontent.com/12507865/107800667-59274a80-6d5f-11eb-83dd-e3e4f84251eb.png)

Like I said in the video you kindly commented on, I will need to come back to actual implementation in April/May.

Let me know what you think, if you have comments.

Thank you.

**Comment by nobiot** [comment]
Actually, your idea: `#+transclude: t :line-range 123-130` might be a better way. 
Let me think it through, when I get back to it.

**Comment by stardiviner** [comment]
I think using source block is a very good idea.
If use your first version mock up source block style. I suggest to use normal header arguments like `:file "file.py" :lines 12-15` etc.
That might be useful for future source block evaluation. What do you think? Even thought evaluation requires more complex things. But at least settle down the styles will be helpful for eval features. So don't need to change in future.

**Comment by nobiot** [comment]
I've just merged v0.2.1 into the main branch with the following new features.

- [Transclude source file into src-block](https://github.com/nobiot/org-transclusion#transclude-source-file-into-src-block)
- [Transclude range of lines for text and source files](https://github.com/nobiot/org-transclusion#transclude-range-of-lines-for-text-and-source-files)

I believe this is what you requested. If you are still using Org-transclusion, I'd appreciate if you could give a try and give me any feedback. Thank you. Closing for now.

**Comment by stardiviner** [comment]
After testing, it works fine on my side. Awesome work! And Thanks. 😄
