### ISSUE TITLE
org-transclusion-live-sync-start-at-point doesn't work. marker doesn't point anywhere

### ISSUE THREAD

**Issue by natask** [nobiot/org-transclusion#75]
I was trying to use `org-transclusion-live-sync-start-at-point` but I am gettering marker doesnt' point anywhere error.
`(org-transclusion-live-sync-source-range-markers-get tc-beg tc-end)` on line 517 fails.
I traced it down to `(set-marker (make-marker)
                        (or (org-element-property :contents-begin parent)
                            (org-element-property :begin parent))
                        src-buf))` on line 1033. It doesn't set the created marker to a vaild one.
I also noticed that the new tranclusion don't have the same colored overlays.

**Comment by nobiot** [comment]
@natask , thank you for trying and reporting.

With the first issue about the marker, it might be an intended error.
Could you please let me know a bit more detail about both of your trancluding and source files?

For example, this screen shot shows a table is in live-sync edit. The regions being edited are indicated by the coloured overlays (blue for translcluding and yellow for the source buffers respectively).
![table-resized](https://user-images.githubusercontent.com/12507865/118391473-be2b5e80-b634-11eb-8b06-0a2ff47fa322.png)

It should work on paragraphs, most of blocks, lists and tables. It does not work directly on the headline title, though (as it is not an element but a property of a headline element among other reasons).
 
Live-sync works selectively on certain Org elements, and if your point is not on an element that works, you often get the message you get about the marker (function [`org-transclusion-get-enclosing-element`](https://github.com/nobiot/org-transclusion/blob/main/org-transclusion.el#L1150) documents this at the moment).

Or... Yes, it could be a program defect. Detail about the elements you worked on to see the error helps me determine if it's a program defect.

In any case, I'll try to improve the error message and documentation. Thanks for your feedback.

Regarding the overlays for read-only transclusion and source regions, they are no longer overlays but text-properties. This is so that undo operations would work more intuitively. Overlays get removed when undo is done; text-properties remain.

I'm still toying with different UI options to indicate transclusion and source regions.

At the moment, you should see a fringe like this (a vertical bar on the left side of the transclusion in this example). If you don't have a margin like I do, you might not see it properly. It's propertized so a dark mode should also show it.

I would love a better idea. This option does not work well with `org-indent-mode` as it is currently done.

![figure](https://raw.githubusercontent.com/nobiot/org-transclusion/main/resources/2021-05-09T190918.png)

**Comment by nobiot** [comment]
@natask  based on your comment, I have reviewed the code. 
66f1d98 is an attempt to do a little more useful error handling.

Thank you again for your feedback. Hopefully this commit is one step better.

**Comment by natask** [comment]
@nobiot thanks for the prompt response.
I was attempting to live edit a source block within a headline link. Regular text within the headline can be live edited. I didn't realize source blocks weren't currently supported.

On the point of UI, I prefer the change in background color. That is what I liked about overlays. It was clear to me which sections where transcluded and that I can call "edit src" on. In my current setup, I don't see the fridge well. My monitor is large so I look at the fridge at an angle and the color differential is minor. Making it thicker and increasing contrast maybe sufficient.

**Comment by nobiot** [comment]
Thanks for the screen shot; easy for me to visualize the issue.

One thing I could suggest within the current version (in addition to your ideas) is to use faces `org-transclusion-fringe` and `org-transclusion-source-fringe`. See an example I have just done below. Both of these faces are "empty" by default; adding background colours to them give you this (on the left is a transclusion; on the right, its source). 

You can also add a foreground colour to change the colour of the fringe bitmap. This way, you can set the fringe filled with a single colour. 

![image](https://user-images.githubusercontent.com/12507865/118443158-de6a2480-b6eb-11eb-81d0-a2778ed5f779.png)

What do you think?

**Comment by nobiot** [comment]
Closing for now.. Thank you. Let me know if you have more issues -- perhaps a new issue based on v0.2.0. Appreciate your feedback as always.
